### ISSUE TITLE
change protein score for red clover to 'high'

### ISSUE THREAD

**Issue by amberfoam** [fo-am/sward-android-app#120]
3 people have expressed concern about it being intermediate and, as 7 studies found it to be intermediate and 2 found it to be high, I  think we can go either way with this one

**Comment by nebogeo** [comment]
@bethanstagg I can change this to high, but then the 7 agreed/2 disagreed is wrong - so maybe some explanation text is needed here?

**Comment by bethanstagg** [comment]
Can we change text to 'Intermediate in 7 studies, high in 2 studies'?
I think that works with the 'thumbs up'?
Could add ' experts agreed score should be 'high'?

This makes me wonder if all trait drop-downs should be in the form of 'high in x studies, low in y studies' to keep it consistent with red clover protein and all the 'horizontal thumbs (instead of 'x studies agreed, y studies disagreed'), what do you think - presumably  that's a lot of editing though
