### ISSUE TITLE
Qu. for Bethan & co. - change trait titles? If says 'high digestibility' people will read it as high digestibility. The 'high' isn't needed.

### ISSUE THREAD

**Issue by amberfoam** [fo-am/sward-android-app#41]

**Comment by bethanstagg** [comment]
So does that mean you think we should remove the 'high' from 'protein', 'digestibility', 'minerals', 'relative yield'? I was trying to address the fact that (1) the rest of traits were in a 'positive state' but these ones were in a 'neutral state', (2) we want thumbs to mean 'excellent, good, ok' rather than 'good, ok, bad'.

**Comment by amberfoam** [comment]
The problem is that it reads as 'high digestibility' regardless of what the colour/thumb are saying, so something more neutral for the headings will probably be less confusing for people?

**Comment by bethanstagg** [comment]
Perhaps we should leave it for now and see what response is during testing? If we lose 'high' from 'digestibility' don't you think we should lose it from those other traits too?

**Comment by amberfoam** [comment]
Sure, and yes!

**Comment by bethanstagg** [comment]
But I agree we should probably go back to what it was originally
